### ISSUE TITLE
Open OAM GUI in network explorer using oamIp 

### ISSUE THREAD

**Issue by noormohammedli** [III-5GC/III-5GC-Free-Trial#1]
Hello Sir, 
I did all the steps based on the installation file, and everything is done successfully without any error. 
I have two question: 
1- In my ubuntu, i dont have eth0, eth1 so i used enp0s8 insted of eth0 and enp0s3 insted of eth1. 
./run.sh -nic1 enp0s8 \
 -oamIp 192.168.1.10 \
 -sbi 192.168.1.0/24 \
 -sbiGw 192.168.1.254 \
 -nic2 enp0s3 \
 -natIp 140.92.13.5 \
 -nat 140.92.13.0/24 \
 -natGw 140.92.13.254

In this case, the containers (netcontainer and oam) done without any error and both of them up.
On the other hand, when I tried to open OAM GUI with the  -oamIp 192.168.1.10  is not working. 

How can I get access to the OAM GUI? 
Could you please help me? 

Regards, 
Noor

**Comment by III-5GC** [comment]
Hello Noor
I would like to thank you for using our 5GC solution, and be sorry for replying delay.

Since there is no error while you started the natcontainer and oam, I suggest you could check the their status by the command
`docker ps`
![image](https://user-images.githubusercontent.com/68258397/98371894-de6fd480-2077-11eb-825f-9dae29b8b0b5.png)
A command `docker exec -it oam bash` could help you to access the OAM container, and then `ps aux`
![image](https://user-images.githubusercontent.com/68258397/98372953-80dc8780-2079-11eb-871d-1b074a82f883.png)
It means that OAM GUI is working well, we can check the networking later.

If nothing shows on your terminal on first step, please try `docker ps -a`, the OAM container should have a status "Exited", please show us the logs of OAM container `docker logs oam` . We could check into that then.

For your networking, please make sure that your network interfaces enp0s8 and enp0s3 are wire-plugged and enabled.
You can utilizing `ethtool enp0s8` and `ifconfig enp0s8`.
![image](https://user-images.githubusercontent.com/68258397/98373613-7b337180-207a-11eb-907a-1d381c92d956.png)
![image](https://user-images.githubusercontent.com/68258397/98373631-85557000-207a-11eb-9b61-6e555f5fe59f.png)
Please check if the "Link detected" is "yes".

Thank you again

**Comment by noormohammedli** [comment]
Hello Sir,

Thank you for your replay. 
I checked all the above commend with the code that I did it before and I still have a problem with OAM GUI. 
When I tried to open OAM GUI with the -oamIp 192.168.1.10 is not working. 
Do I need to use port number with it or just -->> http://192.168.1.10. 

Regards, 
Noor

<img width="818" alt="Screenshot 2020-11-08 at 1 57 12 pm" src="https://user-images.githubusercontent.com/34620715/98466923-7251b580-21ca-11eb-86ea-2afa6b8881eb.png">
<img width="1192" alt="Screenshot 2020-11-08 at 1 50 03 pm" src="https://user-images.githubusercontent.com/34620715/98466924-754ca600-21ca-11eb-95a5-dc4d819f30c7.png">
<img width="996" alt="Screenshot 2020-11-08 at 1 47 43 pm" src="https://user-images.githubusercontent.com/34620715/98466926-7a115a00-21ca-11eb-8e4c-dfa3d36b7ef5.png">

**Comment by III-5GC** [comment]
Hello Noor,

I noticed there were two permition deny I have not seen before while you created the OAM and NAT containers.
![image](https://user-images.githubusercontent.com/68258397/98495981-670a9280-227b-11eb-9788-7b0eb599a33f.png)
Hence I recommend using a root role via `sudo -s`, and create containers again.

It seams your OAM works well, please show me logs of `ethtool enp0s8` and `ifconfig enp0s8`.
I would like to check If the network inteface enp0s8 is assigned an IP 192.168.1.x , and "Link detected" is "yes".

I also noticed that you installed the OAM&NAT over a ubuntu desktop version, so you might execute the firefox in the same server, am I correct?
Since the container network mode we utilized was macvlan, based on this premise, it is hard to access the container's IP from host. (I take a guess that you can not ping container IP 192.168.1.10 from host server 192.168.1.x, right?) 

Here is an quick solution, generally, there is a default container network bridge, "bridge", `docker network ls`
![image](https://user-images.githubusercontent.com/68258397/98503017-8232cd80-228e-11eb-9070-7a2dc105b2f6.png)

Inspect it will get you an IP subnet, `docker network inspect bridge`
![image](https://user-images.githubusercontent.com/68258397/98503058-9ecf0580-228e-11eb-9f6f-996c891153d3.png)

Utilizing the following command to add another network interface for your OAM and check its IP:
`docker network connect bridge oam`    &     `docker exec -it oam ifconfig`
![image](https://user-images.githubusercontent.com/68258397/98503199-e6ee2800-228e-11eb-85f8-0d4041f69949.png)

Now, please enter the new IP other than 192.168.1.10 in your firefox, I hope it could solve your problem.

Any question please let me know

Thanks

**Comment by noormohammedli** [comment]
Hello Sir, 

Thank you for your replay, your explanation very good and useful for me. 

Now it’s work, I could access the OAM GUI from my firefox using 172.17.x.x address after I added the network bridge to the OAM container. 

In addition, you are correct I use the same server and I installed them over a ubuntu-desktop. 

In your example with -nic2, you put eno1. 

And when I run the example I but enp0s3 which is the second network interface that I got from the ifconfig on ubuntu. 

So, if enp0s3 corrects, is that means the NAT IP address will also belong to the same range of the network interface 
or what I did as it is below was right if I want to access it from another server.

-nic2 enp0s3 
-natIp 140.92.13.5 
-nat 140.92.13.0/24 
-natGw 140.92.13.254
 
As a result, of what I have done 
I access the OAM GUI form the Firefox, Form the OAM container I can ping AMF, SMF, PCF and UPF 

And because I use the same server I added a network bridge to the NAT and I accessed to them the IP address that I get. 

With your application, you added a set of users, How can I make one of these users access to the internet through your OAM-5GC? 

If you know a way that's help me to deal with uses and the network slice setting. Or, specify a user for specific SST that will be extremely helpfull for me. 

Regards,

**Comment by III-5GC** [comment]
Hello, Noor

We are glad that your problem was solved. 
Thanks to you, we fixed the mistyped and added the workround to the instruction.

> With your application, you added a set of users, How can I make one of these users access to the internet through your OAM-5GC?

I am a little bit confused here, what did you mean me adding a set of users? Did you mean adding UE info, such as IMSI and UE key?
If so, you might have some misunderstanding about our project.
In this project, we presented a trial 5G core network only. The IMSI and UE key only means the informations of SIM card that 5G core network needed, it will not create a simulated user. 
If you want to test or verify our 5G core network, you might have to prepare your own gNB (5G base station) and UE (5G mobile phone), or even a simulator that can create both. Then giving the information of SIM card you used, that is IMSI, Key, OP or OPc, to our 5G core network. After registration procedure complete, your UE can really access to the internet via gNB, 5GC, and NAT.

Regard

**Comment by noormohammedli** [comment]
> Hello, Noor
> 
> We are glad that your problem was solved.
> Thanks to you, we fixed the mistyped and added the workround to the instruction.
> 
> > With your application, you added a set of users, How can I make one of these users access to the internet through your OAM-5GC?
> 
> I am a little bit confused here, what did you mean me adding a set of users? Did you mean adding UE info, such as IMSI and UE key?
> If so, you might have some misunderstanding about our project.
> In this project, we presented a trial 5G core network only. The IMSI and UE key only means the informations of SIM card that 5G core network needed, it will not create a simulated user.
> If you want to test or verify our 5G core network, you might have to prepare your own gNB (5G base station) and UE (5G mobile phone), or even a simulator that can create both. Then giving the information of SIM card you used, that is IMSI, Key, OP or OPc, to our 5G core network. After registration procedure complete, your UE can really access to the internet via gNB, 5GC, and NAT.
> 
> Regard

Hello, 
Thank you for the explanation, you made it clear for me now. 
Regards,
